import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "styles/Home.module.css";
import ChangeComponent from "components/ChangeComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <ChangeComponent />
        </div>
      </main>
    </>
  );
}
